/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
/*Turning on LED3 coding from scratch configuring and masking the pheriperal registers*/
#include <stdint.h>

int main(void)
{
	uint32_t *pClkctrlreg = (uint32_t*)0x4002104C;
	uint32_t *pPortBmodereg = (uint32_t*)0x48000400;
	uint32_t *pPortBoutreg = (uint32_t*)0x48000414;

	//1. Enable the clock for GPIOB pheripheral in the AHB2ENR
	//uint32_t temp = *pClkctrlreg;  //read operation
	//temp = temp | 0x02;			   //modify
	//*pClkctrlreg = temp;			//write
	*pClkctrlreg |= 0x02;			//same as above but in shorten notation

	//2. Configure the mode of the IO pin as output
	// clear the 7 and 6 bit positions
	*pPortBmodereg &= 0xFFFFFF3F;
	// set the 6 position as 1
	*pPortBmodereg |= 0x00000040;

	//3. set 3rd bit of the output data register to make I/O pin3 high
	*pPortBoutreg |= 0x0008;

	while(1);
}
